// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../data/modules/contacts/models/index/index.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 8112653325472836753),
      name: 'ContactLocalDTO',
      lastPropertyId: const IdUid(5, 3655887801734441228),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 815807839235128706),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 4371220954946966435),
            name: 'phoneNumber',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7817287165433369464),
            name: 'firstName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4623592631222861661),
            name: 'lastName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3655887801734441228),
            name: 'addresses',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 8112653325472836753),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [8546696811071002598],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        6654885185958138802,
        3592246120759000123,
        7069154785718390314,
        6763429425194943338,
        5936468917298024360,
        2595318710007490632
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ContactLocalDTO: EntityDefinition<ContactLocalDTO>(
        model: _entities[0],
        toOneRelations: (ContactLocalDTO object) => [],
        toManyRelations: (ContactLocalDTO object) => {},
        getId: (ContactLocalDTO object) => object.id,
        setId: (ContactLocalDTO object, int id) {
          if (object.id != id) {
            throw ArgumentError('Field ContactLocalDTO.id is read-only '
                '(final or getter-only) and it was declared to be self-assigned. '
                'However, the currently inserted object (.id=${object.id}) '
                "doesn't match the inserted ID (ID $id). "
                'You must assign an ID before calling [box.put()].');
          }
        },
        objectToFB: (ContactLocalDTO object, fb.Builder fbb) {
          final phoneNumberOffset = fbb.writeString(object.phoneNumber);
          final firstNameOffset = fbb.writeString(object.firstName);
          final lastNameOffset = object.lastName == null
              ? null
              : fbb.writeString(object.lastName!);
          final addressesOffset = object.addresses == null
              ? null
              : fbb.writeString(object.addresses!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, phoneNumberOffset);
          fbb.addOffset(2, firstNameOffset);
          fbb.addOffset(3, lastNameOffset);
          fbb.addOffset(4, addressesOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ContactLocalDTO(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              phoneNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              firstName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              lastName: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              addresses: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ContactLocalDTO] entity fields to define ObjectBox queries.
class ContactLocalDTO_ {
  /// see [ContactLocalDTO.id]
  static final id =
      QueryIntegerProperty<ContactLocalDTO>(_entities[0].properties[0]);

  /// see [ContactLocalDTO.phoneNumber]
  static final phoneNumber =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[1]);

  /// see [ContactLocalDTO.firstName]
  static final firstName =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[2]);

  /// see [ContactLocalDTO.lastName]
  static final lastName =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[3]);

  /// see [ContactLocalDTO.addresses]
  static final addresses =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[4]);
}
