// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../data/modules/contacts/models/index/index.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6960171546517005620),
      name: 'ContactLocalDTO',
      lastPropertyId: const IdUid(9, 3879656536786207578),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7702738801340470857),
            name: 'contactID',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 5008227660929283138),
            name: 'firstName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5608915629935242513),
            name: 'lastName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2439936305069932487),
            name: 'streetAddress1',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1465829822253974363),
            name: 'streetAddress2',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3975266680517505517),
            name: 'city',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 7174731646409150389),
            name: 'state',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 5640961840068594806),
            name: 'zipCode',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 3879656536786207578),
            name: 'phoneNumber',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 6960171546517005620),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ContactLocalDTO: EntityDefinition<ContactLocalDTO>(
        model: _entities[0],
        toOneRelations: (ContactLocalDTO object) => [],
        toManyRelations: (ContactLocalDTO object) => {},
        getId: (ContactLocalDTO object) => object.contactID,
        setId: (ContactLocalDTO object, int id) {
          if (object.contactID != id) {
            throw ArgumentError('Field ContactLocalDTO.contactID is read-only '
                '(final or getter-only) and it was declared to be self-assigned. '
                'However, the currently inserted object (.contactID=${object.contactID}) '
                "doesn't match the inserted ID (ID $id). "
                'You must assign an ID before calling [box.put()].');
          }
        },
        objectToFB: (ContactLocalDTO object, fb.Builder fbb) {
          final firstNameOffset = fbb.writeString(object.firstName);
          final lastNameOffset = object.lastName == null
              ? null
              : fbb.writeString(object.lastName!);
          final streetAddress1Offset = object.streetAddress1 == null
              ? null
              : fbb.writeString(object.streetAddress1!);
          final streetAddress2Offset = object.streetAddress2 == null
              ? null
              : fbb.writeString(object.streetAddress2!);
          final cityOffset =
              object.city == null ? null : fbb.writeString(object.city!);
          final stateOffset =
              object.state == null ? null : fbb.writeString(object.state!);
          final zipCodeOffset =
              object.zipCode == null ? null : fbb.writeString(object.zipCode!);
          final phoneNumberOffset = fbb.writeString(object.phoneNumber);
          fbb.startTable(10);
          fbb.addInt64(0, object.contactID);
          fbb.addOffset(1, firstNameOffset);
          fbb.addOffset(2, lastNameOffset);
          fbb.addOffset(3, streetAddress1Offset);
          fbb.addOffset(4, streetAddress2Offset);
          fbb.addOffset(5, cityOffset);
          fbb.addOffset(6, stateOffset);
          fbb.addOffset(7, zipCodeOffset);
          fbb.addOffset(8, phoneNumberOffset);
          fbb.finish(fbb.endTable());
          return object.contactID;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ContactLocalDTO(
              contactID:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              phoneNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 20, ''),
              firstName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              lastName: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              streetAddress1: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              streetAddress2: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              city: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              state: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              zipCode: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 18));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ContactLocalDTO] entity fields to define ObjectBox queries.
class ContactLocalDTO_ {
  /// see [ContactLocalDTO.contactID]
  static final contactID =
      QueryIntegerProperty<ContactLocalDTO>(_entities[0].properties[0]);

  /// see [ContactLocalDTO.firstName]
  static final firstName =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[1]);

  /// see [ContactLocalDTO.lastName]
  static final lastName =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[2]);

  /// see [ContactLocalDTO.streetAddress1]
  static final streetAddress1 =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[3]);

  /// see [ContactLocalDTO.streetAddress2]
  static final streetAddress2 =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[4]);

  /// see [ContactLocalDTO.city]
  static final city =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[5]);

  /// see [ContactLocalDTO.state]
  static final state =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[6]);

  /// see [ContactLocalDTO.zipCode]
  static final zipCode =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[7]);

  /// see [ContactLocalDTO.phoneNumber]
  static final phoneNumber =
      QueryStringProperty<ContactLocalDTO>(_entities[0].properties[8]);
}
